services:
  db:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banque_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d banque_db"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - app_network

  app:
    build: ./tp1jdbc/
    container_name: code-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/banque_db
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - app_network
    env_file:
      - identifiers.env
    volumes:
      - ./logs:/app/logs

networks:
  app_network:
    driver: bridge
